### ISSUE TITLE
Unable to style custom components based on attributes

### ISSUE THREAD

**Issue by angelsalazar** [trailheadapps/lwc-recipes#93]
**What is missing from the application?
LWC library currently does not allow to style components based on attributes like the Native implementation of Custom elements.

Writing the following css rule

```css
:host([covered]) {
    visibility: visible;
    width: 100%;
    transition: 0.3s;
    transform: translateX(0);
}
```
outputs the following error

`CssSyntaxError: LWC1009: postcss-plugin-lwc: /home/sfdc/tools/lwc/0.34.7/drawer.css:11:7: Invalid usage of attribute selector "covered". For validation purposes, attributes that are not global attributes must be associated with a tag name when used in a CSS selector. (e.g., "input[min]" instead of "[min]")`

**Describe the solution you'd like**

Writing the css rule shown above should be allowed

**Describe alternatives you've considered**

As a workaround I have implemented a class solution to mimic the feature describe above.

drawer.css

```css
:host {
    display: block;
    position: absolute;
    top:0;
    right: 0;
    height: 100%;
    visibility: hidden;
    overflow: hidden;
}
// this should be :host([covered])
:host.covered {
    visibility: visible;
    width: 100%;
    transition: 0.3s;
    transform: translateX(0);
}

:host .overlay,
:host .slds-panel {
    border-top-right-radius: .25rem;
    border-bottom-right-radius: .25rem;
}

:host .slds-panel_docked {
    display: block;
    visibility: hidden;
    transition: 0.3s ease-in;
    transform: translateX(100%);
    overflow: hidden;
}

// this should be :host([covered]) .overlay
:host.covered .overlay {
    position: absolute;
    background-color: rgba(0, 0, 0, 0.4);
    width: 100%;
    height: 100%;
} 

:host .slds-is-open {
    visibility: visible;
    transform: translateX(0);
}
```

drawer.js

```js

export default class Drawer extends LightningElement {
    @api open = false;
    @api title = 'Header';

    get drawerClass() {
        return (`slds-panel slds-size_medium slds-panel_docked slds-panel_docked-right ${this.open ? 'slds-is-open' : ''}`);
    }

    get isHidden() {
        return this.open === false
    }

    renderedCallback() {
        if (this.open && !this.classList.contains('covered')) {
            this.classList.add('covered');
        } else {
            this.classList.remove('covered');
        }
    }

    handleClose() {
        this.dispatchEvent(new CustomEvent('close'));
    }
}

```

drawer.html

```html
<template>
    <template if:true={open}>
        <div class="overlay"></div>
    </template>
    <div class={drawerClass} aria-hidden={isHidden}>
        <div class="slds-panel__header">
            <h2 class="slds-panel__header-title slds-text-heading_small slds-truncate" 
                title={title}>
                {title}
            </h2>
            <lightning-button-icon 
                variant="bare"
                class="slds-panel__close" 
                size="small" 
                title="Collapse Panel Header"
                icon-name="utility:close"
                alternative-text="Collapse Panel Header"
                onclick={handleClose}>
            </lightning-button-icon>
        </div>
        <div class="slds-panel__body">
            <slot></slot>
        </div>
    </div>
</template>
```

**Additional context**

Example of the expected behavior using the native implementation.

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>

</head>
<body>
 <x-test></x-test>
 
 <br/>
 
 <x-test id="target" ></x-test>
 <button>toogle inversed</button>
</body>
</html>
```

```javascript
const template = document.createElement('template');

template.innerHTML = `
  <style>
    :host {
      display: block;
      color: black;
      background: #fff;
    }

    :host([inversed]) {
      color: white;
      background: #000;
    }
  </style>

  I am
`;

class Test extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
    this.shadowRoot.appendChild(
      template.content.cloneNode(true)
    );
  }
  
  
  static get observedAttributes() { return ['inversed']; }
  
  attributeChangedCallback(name, oldValue, newValue) {
    // sync property
    this.inserved = (newValue === 'inserved')
  }
}

customElements.define('x-test', Test);

const target = document.getElementById('target');

document
  .querySelector('button')
  .addEventListener('click', () => {
    if (target.hasAttribute('inversed')) {
       target.removeAttribute('inversed');
    } else {
       target.setAttribute('inversed', 'inserved');
    }
    console.log(target.inserved);
  });
```
[Demo](https://jsbin.com/gutajacesa/edit?html,js,console,output)
